# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      #CC_TEST_REPORTER_ID: 3e54...
      #HEROKU_API_KEY: abee...
      #HEROKU_APP_NAME: ...
      CHROME_BIN: "/usr/bin/google-chrome"

    docker:
      # specify the version you desire here
      - image: circleci/node:10.2.1-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - roldevs_bot-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - roldevs_bot-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: roldevs_bot-{{ checksum "package.json" }}

      # run tests!
      - run:
          command: npm test
          when: always
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

